version: 0.0.{build}
configuration: Release
skip_tags: true
clone_depth: 1
cache: C:\Users\appveyor\.nuget\packages
before_build:
- dotnet restore
build_script:
- dotnet pack src\Banshee\project.json -c Release -o artifacts
test_script:
- dotnet test src\Banshee.Tests\project.json -c Release
artifacts:
- path: '**\*.nupkg'
- path: ConsoleOut.log
- path: ConsoleError.log