version: 0.0.{build}
configuration: Release
skip_tags: true
clone_depth: 1
cache: C:\Users\appveyor\.nuget\packages
before_build:
- ps: dotnet restore
after_build:
- dotnet pack src\Banshee\project.json --no-build -c Release
test_script:
- dotnet test src\Banshee.Tests\project.json --no-build -c Release
artifacts:
- path: '**\*.nupkg'
- path: ConsoleOut.log
- path: ConsoleError.log