-
  branches:
    except:
      - stable
  version: '{branch}-build{build}'
  skip_tags: true
  clone_depth: 1
  cache: C:\Users\appveyor\.nuget\packages
  configuration:
    - Debug
    - Release
  before_build:
    - ps: dotnet --info
    - ps: dotnet restore
    - ps: $env:VERSION_SUFFIX = 'build' + "$env:APPVEYOR_BUILD_NUMBER".PadLeft(4, "0")
  build_script:
    - ps: dotnet pack src\Banshee\project.json -c $env:CONFIGURATION -o artifacts --version-suffix $env:VERSION_SUFFIX
  test_script:
    - ps: dotnet test src\Banshee.Tests\project.json -c $env:CONFIGURATION
  artifacts:
    - path: 'artifacts\*.nupkg'
#  deploy:
#    on:
#      configuration: Debug
#    provider: NuGet
#    api_key:
#      secure: 4eGPThK/wSpRmfINQgAGQZD/e8r6FKRfp0SN4nB5/FBTHKJ1xIf/BK3/Iz5csDFm
#    artifact: /.*\.nupkg/
-
  branches:
    only:
      - stable
  version: '{branch}-build{build}'
  skip_tags: true
  clone_depth: 1
  cache: C:\Users\appveyor\.nuget\packages
  configuration: Release
  before_build:
    - ps: dotnet --info
    - ps: dotnet restore
  build_script:
    - ps: dotnet pack src\Banshee\project.json -c $env:CONFIGURATION -o artifacts
  test_script:
    - ps: dotnet test src\Banshee.Tests\project.json -c $env:CONFIGURATION
  artifacts:
    - path: 'artifacts\*.nupkg'
#  deploy:
#    provider: NuGet
#    api_key:
#      secure: 4eGPThK/wSpRmfINQgAGQZD/e8r6FKRfp0SN4nB5/FBTHKJ1xIf/BK3/Iz5csDFm
#    artifact: /.*\.nupkg/